<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Admin_fa fa-cog</name>
   <tag></tag>
   <elementGuidId>db8e14cf-6bde-47ad-bc7f-4c86d141f49f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bisadmin-container']/div[2]/div/div/div/div[2]/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.far.fa-angle-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>afa3f5f8-af56-4c55-b7d8-8c213fd0e158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>far fa-angle-down</value>
      <webElementGuid>0c58b7bc-e304-4a66-b16a-963c4cd31e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d25a3b7d-5daa-4777-abfd-9a955016f763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisadmin-container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-4 col-lg-6 col-md-12 col-sm-12&quot;]/div[@class=&quot;settings-item-wrapper&quot;]/div[@class=&quot;settings-item-head&quot;]/div[@class=&quot;settings-item-right-side&quot;]/span[@class=&quot;toggle-arrow arrow-down&quot;]/i[@class=&quot;far fa-angle-down&quot;]</value>
      <webElementGuid>5e258dfc-27bc-4218-90b1-fbf5d20088b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bisadmin-container']/div[2]/div/div/div/div[2]/span/i</value>
      <webElementGuid>f0524338-a620-44c4-8554-7438944b5298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/span/i</value>
      <webElementGuid>712e6233-efe7-4b81-a160-ed7e133db42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactRoot']/div/header/div/div[2]/div/a/i</value>
      <webElementGuid>b39075c6-6712-4900-98b5-ec715ae6d09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/i</value>
      <webElementGuid>21fe3146-52db-4de5-a1df-2f479ca84a50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
