<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Admin_fa fa-cog</name>
   <tag></tag>
   <elementGuidId>db8e14cf-6bde-47ad-bc7f-4c86d141f49f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bisadmin-container']/div[2]/div/div/div/div[2]/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.far.fa-angle-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8f869a8c-80ff-46c6-85a8-a055f9de5dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>far fa-angle-down</value>
      <webElementGuid>6e30e25e-22b1-4587-9fe1-20dc3cf6e4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4bb9cfb0-d953-476a-8b9d-bd25e3c7a07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bisadmin-container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-4 col-lg-6 col-md-12 col-sm-12&quot;]/div[@class=&quot;settings-item-wrapper&quot;]/div[@class=&quot;settings-item-head&quot;]/div[@class=&quot;settings-item-right-side&quot;]/span[@class=&quot;toggle-arrow arrow-down&quot;]/i[@class=&quot;far fa-angle-down&quot;]</value>
      <webElementGuid>acc0d49f-097b-48d7-8021-6c7308dd6f00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bisadmin-container']/div[2]/div/div/div/div[2]/span/i</value>
      <webElementGuid>cb4b3164-8008-4d46-9719-1dcc32875ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/span/i</value>
      <webElementGuid>b33008e3-27d5-487d-9c7f-87c831ac1981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactRoot']/div/header/div/div[2]/div/a/i</value>
      <webElementGuid>e16c8c7a-c07b-4026-927a-f5885583f9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/i</value>
      <webElementGuid>e35b3a05-48d3-4800-ac75-b402029d45dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
