<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birthdate_BirthDate1</name>
   <tag></tag>
   <elementGuidId>3ea96b08-6365-47f0-9b5f-30e5b632f887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BirthDate1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BirthDate1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65069109-55d1-481a-83cb-dc880cca1937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>724d39ef-0afc-40f4-a6c0-0e569bf01876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>74b9a21b-4352-43e9-99e7-de3f0e6a1c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vmpUserObj.birthdateencrypt == 1</value>
      <webElementGuid>65803679-3bee-4429-956e-1f4552f37dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BirthDate1</value>
      <webElementGuid>87297ddf-f5d5-4763-ae85-d8cd74885752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BirthDate1</value>
      <webElementGuid>9fff5a50-984b-4dd8-9f5e-8f9940499cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmpUserObj.birthdateenc</value>
      <webElementGuid>73426064-8d0a-410d-8d2c-08922481a5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DatePickerClass form-control ng-pristine ng-valid ng-scope ng-not-empty ng-touched</value>
      <webElementGuid>31feb8e4-e4bd-47e1-9b9e-c837d1a88041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>
                              if (this.hasAttribute('readonly')) {
                                this.removeAttribute('readonly');
                                // fix for mobile safari to show virtual keyboard
                                this.blur();
                                this.focus();
                              }
                            </value>
      <webElementGuid>a2865adc-6ce4-4fc0-8a4c-95365163f087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>499c665d-6ba8-465b-9974-34c4d2a0603e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BirthDate1&quot;)</value>
      <webElementGuid>cdbbc58d-1160-4249-8429-5dcbd3afc452</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BirthDate1']</value>
      <webElementGuid>57c32a6a-9669-47e3-952d-f1dd9a6ad134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div/div[2]/div[14]/div/div/input</value>
      <webElementGuid>0bad9cf8-1782-4472-95fe-95cb03751ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/input</value>
      <webElementGuid>f61838ef-a684-4964-b5a1-4f382afb672c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'BirthDate1' and @id = 'BirthDate1']</value>
      <webElementGuid>72a45a2f-242e-41f0-9274-c3ffb6ee076a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
