<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birthdate_BirthDate</name>
   <tag></tag>
   <elementGuidId>a2811d3e-f2ab-4a2b-83d2-39735e9017d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'BirthDate' and @id = 'BirthDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BirthDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//label[@for='BirthDateDemographics']//following::div//input)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a01b19a8-8b56-490d-84ee-702c6faad1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43e28c3f-7a4b-48c8-b3f5-1d5eb2c308c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BirthDate</value>
      <webElementGuid>be6f14f8-b88f-41e4-adaf-739edb684b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!(vmpUserObj.birthdateencrypt == 1)</value>
      <webElementGuid>7795c1b7-1ce9-4b1c-98c3-ffac08df8814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-datepicker-popup</name>
      <type>Main</type>
      <value>dd-MMMM-yyyy</value>
      <webElementGuid>18f3a3c2-9b10-4913-894b-42fb8afcfea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmpUserObj.birthdate</value>
      <webElementGuid>92af601f-93ec-41bd-872c-101a531d4c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>checkDobMaxDateExceeded()</value>
      <webElementGuid>394df929-4515-4772-9b30-25dda6f52136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-open</name>
      <type>Main</type>
      <value>popup.popup1.opened</value>
      <webElementGuid>b0411966-1147-4ba6-b291-e0b9f11d07d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datepicker-options</name>
      <type>Main</type>
      <value>birthDateOptions</value>
      <webElementGuid>7825261c-1690-4a85-81c8-06e077beb484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>close-text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>8fe051ee-c923-4dfa-b913-d9fdf5866cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt-input-formats</name>
      <type>Main</type>
      <value>altInputFormats</value>
      <webElementGuid>5c1c3a42-a609-4847-8211-659062691f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BirthDate</value>
      <webElementGuid>74e17ced-c3e5-46be-a971-51386116cabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DatePickerClass form-control ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope ng-valid-date ng-not-empty</value>
      <webElementGuid>580a8fa8-9c67-4b6a-babe-cd65d29f676d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9abdcf4a-f76b-4dba-9a64-30779068b426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BirthDate&quot;)</value>
      <webElementGuid>d5049434-f975-4737-b4ac-2835bf384fa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>523148ff-b8a6-4404-8424-9e9ffc8fe634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ca794636-9981-4cca-afa0-8d8ef04235da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0fc06d1f-d512-4164-90b8-de94781056fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>dd9ea9cd-b315-42f7-8b10-8c8d9ed4570a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
