<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birthdate_BirthDate</name>
   <tag></tag>
   <elementGuidId>a2811d3e-f2ab-4a2b-83d2-39735e9017d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BirthDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[14]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5fd0909-d1f9-4d86-84d7-0cc3a305b903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b032b61-1100-4813-954c-453f70feb691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BirthDate</value>
      <webElementGuid>faf80f90-08cb-40dc-9f27-0635ca211f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!(vmpUserObj.birthdateencrypt == 1)</value>
      <webElementGuid>8dbf64ec-9140-4a43-abed-9b2cdea43e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-datepicker-popup</name>
      <type>Main</type>
      <value>dd-MMMM-yyyy</value>
      <webElementGuid>2cc72c13-3781-4f85-8e67-70463b167a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmpUserObj.birthdate</value>
      <webElementGuid>7e6db8e8-4aa4-428a-8a71-a853efa2c099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>checkDobMaxDateExceeded()</value>
      <webElementGuid>014ce918-cdeb-40d6-909c-753448767cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-open</name>
      <type>Main</type>
      <value>popup.popup1.opened</value>
      <webElementGuid>39bfdb93-f7b3-44cf-a857-e18714ba088b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datepicker-options</name>
      <type>Main</type>
      <value>birthDateOptions</value>
      <webElementGuid>3e410eff-8342-4dee-91b9-dd98e81a6af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>close-text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>7f26d0f9-5171-42b8-ac4c-23566f3e628f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt-input-formats</name>
      <type>Main</type>
      <value>altInputFormats</value>
      <webElementGuid>de33f806-0dc7-4f5f-aca2-27af60e4f0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BirthDate</value>
      <webElementGuid>5e26c390-2b9d-43a1-b2a6-1b02caa79ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DatePickerClass form-control ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope ng-valid-date ng-not-empty</value>
      <webElementGuid>91de3a96-9c74-4905-888a-b8c71df2c152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>025d53b7-363f-4776-ada0-600ea68b38fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BirthDate&quot;)</value>
      <webElementGuid>cebef37c-f62d-496a-9dc5-3642113622c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BirthDate']</value>
      <webElementGuid>fc1a354e-0f90-43bd-9090-e0ae76646817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/form/div/div/div/div[2]/div[14]/div/div/input</value>
      <webElementGuid>eccb4098-97fc-4c08-86c4-a4f13d61fdd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/input</value>
      <webElementGuid>27551af6-7926-486d-9ccf-7319bffb90bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BirthDate' and @id = 'BirthDate']</value>
      <webElementGuid>1fa302dd-6448-4ebd-ba0d-462645f984e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
