<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Birthdate_switch-slider</name>
   <tag></tag>
   <elementGuidId>d80236aa-17f2-4719-86b0-86990037e607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='custom-toggle-birthdate']/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.switch-slider.checked</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>260764e4-e359-4673-83d1-8b5a5f95c42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch-slider checked </value>
      <webElementGuid>6aa142a0-aa55-4c3e-bd7e-b920a56f4e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-toggle-birthdate&quot;)/label[@class=&quot;horizontal-switch&quot;]/span[@class=&quot;switch-slider checked&quot;]</value>
      <webElementGuid>57653701-f94b-4f5d-954d-094e1ca3342b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='custom-toggle-birthdate']/label/span</value>
      <webElementGuid>aa38271c-2d49-4017-aa5a-12a8e9851b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/label/span</value>
      <webElementGuid>810d560f-be69-4716-bd01-b21f40e5e9b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
