<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BIS Admin tab</name>
   <tag></tag>
   <elementGuidId>43c14f99-e014-4667-a3fb-1918e94f35e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-text-BISAdmin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-text-BISAdmin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ea109f0f-a7bd-498f-a23e-e423cc3a80e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-text-BISAdmin</value>
      <webElementGuid>88bc9b97-59d6-4403-bace-186b5ba0c0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-text reveal</value>
      <webElementGuid>1e68ec90-e3e6-48bd-9f77-4b2899209183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BIS Admin</value>
      <webElementGuid>77904311-29a2-4505-bc0a-bfae3ec6cb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-text-BISAdmin&quot;)</value>
      <webElementGuid>3f15d795-4f50-4f3a-a356-ddc9e29fdcb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='menu-text-BISAdmin']</value>
      <webElementGuid>4461c18c-806e-4d9e-88d8-cfd6bbc2cc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-items-container']/div[7]/div</value>
      <webElementGuid>c64e0239-72f6-4748-aee9-955b0c6d4533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Integration'])[1]/following::div[2]</value>
      <webElementGuid>972f3afc-4644-49cc-bf88-c78d247bbff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Management'])[1]/following::div[4]</value>
      <webElementGuid>84117580-f2bf-4025-96f8-78900910e9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/preceding::div[1]</value>
      <webElementGuid>05b33211-d8b2-450b-b17d-b0d9dfe530fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Information'])[2]/preceding::div[3]</value>
      <webElementGuid>d301a8d4-7270-44eb-9406-eae55091dfa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BIS Admin']/parent::*</value>
      <webElementGuid>ace41fc4-ab52-494a-bfb7-45e85bf62ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div</value>
      <webElementGuid>16f03275-3899-445c-b82c-06f960003d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'menu-text-BISAdmin' and (text() = 'BIS Admin' or . = 'BIS Admin')]</value>
      <webElementGuid>92489331-c96f-46c2-be64-aa622be337a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
