<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Birthdate_switch-slider unchecked</name>
   <tag></tag>
   <elementGuidId>40dddfd8-8232-4fe3-937d-ab0192aa403e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='custom-toggle-birthdate']/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.switch-slider.checked</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e10927ee-484c-40a5-939c-8b0eb14edaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch-slider checked </value>
      <webElementGuid>f8f2c2a0-32fe-41d4-8412-d9f21badf07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-toggle-birthdate&quot;)/label[@class=&quot;horizontal-switch&quot;]/span[@class=&quot;switch-slider checked&quot;]</value>
      <webElementGuid>3d442772-0b6c-4d79-8e3b-1cc9f92a202d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='custom-toggle-birthdate']/label/span</value>
      <webElementGuid>e5a58836-b12a-426b-8b74-fd0a92903c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/label/span</value>
      <webElementGuid>aa6bd4db-5ffb-4573-8929-a65f91742d22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
