<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__prof_img_icon</name>
   <tag></tag>
   <elementGuidId>56c8996a-a204-424c-b62e-84dedc97f7f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='toggleProfileSection()']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@onclick='toggleProfileSection()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.prof_img_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e0aae2f-9a4f-4a63-a407-0750f8d0255f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prof_img_icon</value>
      <webElementGuid>6a48379b-5790-4c02-8004-9af74043f2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@onclick='toggleProfileSection()']</value>
      <webElementGuid>a9952caa-d700-4a52-b4a6-02370a97ac9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='this-header']/div[2]/div[2]/ul/li[2]/div/div</value>
      <webElementGuid>dc030ac7-c571-4d03-8d1d-a649b30dc381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/following::div[2]</value>
      <webElementGuid>a9903d1f-4253-4538-948f-83c5837ff513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::div[1]</value>
      <webElementGuid>16eec90e-2a17-4846-830d-c94b3c9538bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::div[3]</value>
      <webElementGuid>308f4e29-e982-47cf-be70-5f446fa26ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div</value>
      <webElementGuid>44c6dcd2-21cd-432b-bfbb-b10ec0bd2b67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
