<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__prof_img_icon</name>
   <tag></tag>
   <elementGuidId>56c8996a-a204-424c-b62e-84dedc97f7f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.prof_img_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='this-header']/div[2]/div[2]/ul/li[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dcc8eec0-224a-450c-b9b2-e426930d3bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prof_img_icon</value>
      <webElementGuid>dacfbc13-44c1-4030-ab34-6d214985b38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;this-header&quot;)/div[@class=&quot;right_side_wrapper&quot;]/div[@class=&quot;hd_t_rght&quot;]/ul[@class=&quot;header_icons_ul&quot;]/li[2]/div[@class=&quot;head_ico_prof&quot;]/div[@class=&quot;prof_img_icon&quot;]</value>
      <webElementGuid>426159f2-222b-4a34-87cd-1c037ef58b03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='this-header']/div[2]/div[2]/ul/li[2]/div/div</value>
      <webElementGuid>e044fe63-398c-4512-9cbb-779a8164b639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/following::div[2]</value>
      <webElementGuid>11e53769-0218-49c8-931b-9f46829d0ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::div[1]</value>
      <webElementGuid>089e9725-0850-4c5b-aac9-6aa2cb6c9171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::div[3]</value>
      <webElementGuid>8d61d9d1-30a7-4715-b26e-4d2c3b94534d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div</value>
      <webElementGuid>9974ad2f-9f66-4037-8dbf-805ae27516d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
